apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: shopnow
type: Opaque
stringData:
  # Override these values via Jenkins credentials or kubectl before applying
  mongodb-uri: "mongodb://shopnow-user:shopnow-pass@mongodb-service:27017/shopnow?authSource=admin"
  mongodb-root-password: "changeme-root"
  mongodb-username: "shopnow-user"
  mongodb-password: "shopnow-pass"
  mongodb-database: "shopnow"
